[package]
name = "warframe"
version = "0.1.0"
edition = "2021"
description = "An async crate to wrap the Warframe's Worldstate API."
readme = "README.md"
documentation = "https://docs.rs/warframe"
homepage = "https://docs.rs/warframe"
repository = "https://github.com/Mettwasser/warframe.rs"
license = "MIT"

[features]
default = ["worldstate"]
worldstate = []

[dev-dependencies]
clippy = "*"
rustfmt = "*"

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
reqwest = { version = "0.11.22", features = ["json"] }
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = { version = "1.0.108" }