[package]
name = "warframe"
version = "0.1.0"
edition = "2021"

[features]
default = ["worldstate"]
worldstate = []


[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
reqwest = { version = "0.11.22", features = ["json"] }
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = { version = "1.0.108" }